### ISSUE TITLE
DajareStationのロゴのパスが変更された

### ISSUE THREAD

**Issue by averak** [rits-dajare/DaaS#22]
READMEのReferencesにある，DajareStationのロゴ画像が消えているので修正する

**Comment by ygkn** [comment]
テキストじゃあかんの

**Comment by averak** [comment]
もともとシャレオツなロゴ（公式が勧めてたやつ）を表示できたのだけど，それが名残惜しい

**Comment by averak** [comment]
テキストでも問題ないけどね

**Comment by ygkn** [comment]
公式が勧めてたのがなくなったならしゃーない

テキストでかっこよくかくしか

**Comment by averak** [comment]
This is your chance to contribute!!!

**Comment by ygkn** [comment]
develop に PR 投げればいいん

**Comment by averak** [comment]
developは死んでるのでmasterで
